language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - IMAGINE_DRIVER=imagick
  - IMAGINE_DRIVER=gmagick

before_script:
  - travis_retry composer self-update
  - travis_retry composer require satooshi/php-coveralls:~0.6 --prefer-source --no-interaction --dev
  - sudo apt-get remove -y imagemagick libmagickcore-dev libmagickwand-dev
  - sudo apt-get install -y libtiff-dev libjpeg-dev libdjvulibre-dev libwmf-dev pkg-config
  - sh -c "if [ '$IMAGINE_DRIVER' = 'imagick' ]; then
              sh ./tests/travis/imagick.sh
            fi"
  - sh -c "if [ '$IMAGINE_DRIVER' = 'gmagick' ]; then
              sh ./tests/travis/gmagick.sh
            fi"

script: phpunit -c phpunit.xml --coverage-text

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" != *hhvm* ]]; then php vendor/bin/coveralls -v; fi

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
