language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer require satooshi/php-coveralls:~0.6 --prefer-source --no-interaction --dev
  - sudo apt-get remove -y imagemagick libmagickcore-dev libmagickwand-dev
  - sudo apt-get install -y libtiff-dev libjpeg-dev libdjvulibre-dev libwmf-dev pkg-config
  - sh ./tests/travis/imagick.sh
  - sh ./tests/travis/gmagick.sh

script: phpunit -c phpunit.xml --coverage-text

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" != *hhvm* ]]; then php vendor/bin/coveralls -v; fi

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
